import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, useUser, UserButton ,SignIn} from "@clerk/nextjs";
// import Link from "next/link";

import { api } from "~/utils/api";
 
const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();
  const { data } = api.posts.getAll.useQuery()



  console.log(data)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">

        <div >
         <SignIn />

         <UserButton />

         <div className=" text-white">
          {data?.map(post => (<div key={post.id}>{post.content}</div>))}
         </div> 
          
        </div>  
      </main>
    </>
  );
};

export default Home;
